// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.Infrastructure.Data;

#nullable disable

namespace University.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20260702120837_AddThesisUpdateAttachmentMetadata")]
    partial class AddThesisUpdateAttachmentMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "e5a294fd-abcb-4a1c-962c-8a61ed9214d4",
                            Name = "Professor",
                            NormalizedName = "PROFESSOR"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "bfc55cfe-7ccf-44d8-9250-d883c9da8d0c",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "prof-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "prof-1-concurrency",
                            Email = "prof1@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PROF1@UNIV.EDU",
                            NormalizedUserName = "PROF1@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "prof-1-stamp",
                            TwoFactorEnabled = false,
                            UserName = "prof1@univ.edu"
                        },
                        new
                        {
                            Id = "prof-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "prof-2-concurrency",
                            Email = "prof2@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PROF2@UNIV.EDU",
                            NormalizedUserName = "PROF2@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "prof-2-stamp",
                            TwoFactorEnabled = false,
                            UserName = "prof2@univ.edu"
                        },
                        new
                        {
                            Id = "prof-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "prof-3-concurrency",
                            Email = "prof3@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PROF3@UNIV.EDU",
                            NormalizedUserName = "PROF3@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "prof-3-stamp",
                            TwoFactorEnabled = false,
                            UserName = "prof3@univ.edu"
                        },
                        new
                        {
                            Id = "prof-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "prof-4-concurrency",
                            Email = "prof4@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PROF4@UNIV.EDU",
                            NormalizedUserName = "PROF4@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "prof-4-stamp",
                            TwoFactorEnabled = false,
                            UserName = "prof4@univ.edu"
                        },
                        new
                        {
                            Id = "prof-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "prof-5-concurrency",
                            Email = "prof5@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PROF5@UNIV.EDU",
                            NormalizedUserName = "PROF5@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "prof-5-stamp",
                            TwoFactorEnabled = false,
                            UserName = "prof5@univ.edu"
                        },
                        new
                        {
                            Id = "student-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-1-concurrency",
                            Email = "student1@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@UNIV.EDU",
                            NormalizedUserName = "STUDENT1@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-1-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student1@univ.edu"
                        },
                        new
                        {
                            Id = "student-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-2-concurrency",
                            Email = "student2@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@UNIV.EDU",
                            NormalizedUserName = "STUDENT2@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-2-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student2@univ.edu"
                        },
                        new
                        {
                            Id = "student-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-3-concurrency",
                            Email = "student3@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT3@UNIV.EDU",
                            NormalizedUserName = "STUDENT3@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-3-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student3@univ.edu"
                        },
                        new
                        {
                            Id = "student-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-4-concurrency",
                            Email = "student4@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT4@UNIV.EDU",
                            NormalizedUserName = "STUDENT4@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-4-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student4@univ.edu"
                        },
                        new
                        {
                            Id = "student-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-5-concurrency",
                            Email = "student5@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT5@UNIV.EDU",
                            NormalizedUserName = "STUDENT5@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-5-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student5@univ.edu"
                        },
                        new
                        {
                            Id = "student-6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-6-concurrency",
                            Email = "student6@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT6@UNIV.EDU",
                            NormalizedUserName = "STUDENT6@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-6-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student6@univ.edu"
                        },
                        new
                        {
                            Id = "student-7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-7-concurrency",
                            Email = "student7@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT7@UNIV.EDU",
                            NormalizedUserName = "STUDENT7@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-7-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student7@univ.edu"
                        },
                        new
                        {
                            Id = "student-8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-8-concurrency",
                            Email = "student8@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT8@UNIV.EDU",
                            NormalizedUserName = "STUDENT8@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-8-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student8@univ.edu"
                        },
                        new
                        {
                            Id = "student-9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-9-concurrency",
                            Email = "student9@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT9@UNIV.EDU",
                            NormalizedUserName = "STUDENT9@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-9-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student9@univ.edu"
                        },
                        new
                        {
                            Id = "student-10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-10-concurrency",
                            Email = "student10@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT10@UNIV.EDU",
                            NormalizedUserName = "STUDENT10@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-10-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student10@univ.edu"
                        },
                        new
                        {
                            Id = "student-11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-11-concurrency",
                            Email = "student11@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT11@UNIV.EDU",
                            NormalizedUserName = "STUDENT11@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-11-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student11@univ.edu"
                        },
                        new
                        {
                            Id = "student-12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-12-concurrency",
                            Email = "student12@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT12@UNIV.EDU",
                            NormalizedUserName = "STUDENT12@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-12-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student12@univ.edu"
                        },
                        new
                        {
                            Id = "student-13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-13-concurrency",
                            Email = "student13@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT13@UNIV.EDU",
                            NormalizedUserName = "STUDENT13@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-13-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student13@univ.edu"
                        },
                        new
                        {
                            Id = "student-14",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-14-concurrency",
                            Email = "student14@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT14@UNIV.EDU",
                            NormalizedUserName = "STUDENT14@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-14-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student14@univ.edu"
                        },
                        new
                        {
                            Id = "student-15",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "student-15-concurrency",
                            Email = "student15@univ.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT15@UNIV.EDU",
                            NormalizedUserName = "STUDENT15@UNIV.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAECm7pNz7z7vqR0Z5vX2Z7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W5mZ7W=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "student-15-stamp",
                            TwoFactorEnabled = false,
                            UserName = "student15@univ.edu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "prof-1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "prof-2",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "prof-3",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "prof-4",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "prof-5",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "student-1",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-3",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-4",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-5",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-6",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-7",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-8",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-9",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-10",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-11",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-12",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-13",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-14",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "student-15",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("University.Domain.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudentId", "ProfessorId")
                        .IsUnique();

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProfessorId = 3,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("University.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("UpdateId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("University.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Computer Science",
                            Expertise = "Machine Learning",
                            UserId = "prof-1"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Mathematics",
                            Expertise = "Algebra",
                            UserId = "prof-2"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Physics",
                            Expertise = "Quantum",
                            UserId = "prof-3"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Chemistry",
                            Expertise = "Organic",
                            UserId = "prof-4"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Biology",
                            Expertise = "Genetics",
                            UserId = "prof-5"
                        });
                });

            modelBuilder.Entity("University.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "AI",
                            SupervisorId = 1,
                            UserId = "student-1"
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Theoretical",
                            SupervisorId = 2,
                            UserId = "student-2"
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Nuclear",
                            SupervisorId = 3,
                            UserId = "student-3"
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Synthetic",
                            SupervisorId = 4,
                            UserId = "student-4"
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Molecular",
                            SupervisorId = 5,
                            UserId = "student-5"
                        },
                        new
                        {
                            Id = 6,
                            EnrollmentDate = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "AI",
                            SupervisorId = 1,
                            UserId = "student-6"
                        },
                        new
                        {
                            Id = 7,
                            EnrollmentDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Theoretical",
                            SupervisorId = 2,
                            UserId = "student-7"
                        },
                        new
                        {
                            Id = 8,
                            EnrollmentDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Nuclear",
                            SupervisorId = 3,
                            UserId = "student-8"
                        },
                        new
                        {
                            Id = 9,
                            EnrollmentDate = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Synthetic",
                            SupervisorId = 4,
                            UserId = "student-9"
                        },
                        new
                        {
                            Id = 10,
                            EnrollmentDate = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Molecular",
                            SupervisorId = 5,
                            UserId = "student-10"
                        },
                        new
                        {
                            Id = 11,
                            EnrollmentDate = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "AI",
                            SupervisorId = 1,
                            UserId = "student-11"
                        },
                        new
                        {
                            Id = 12,
                            EnrollmentDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Theoretical",
                            SupervisorId = 2,
                            UserId = "student-12"
                        },
                        new
                        {
                            Id = 13,
                            EnrollmentDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Nuclear",
                            SupervisorId = 3,
                            UserId = "student-13"
                        },
                        new
                        {
                            Id = 14,
                            EnrollmentDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Synthetic",
                            SupervisorId = 4,
                            UserId = "student-14"
                        },
                        new
                        {
                            Id = 15,
                            EnrollmentDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Specialization = "Molecular",
                            SupervisorId = 5,
                            UserId = "student-15"
                        });
                });

            modelBuilder.Entity("University.Domain.Entities.ThesisTopicAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TopicId")
                        .IsUnique();

                    b.ToTable("ThesisTopicAssignments");
                });

            modelBuilder.Entity("University.Domain.Entities.ThesisUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AttachmentSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ThesisUpdates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("University.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("University.Domain.Entities.Professor", "Professor")
                        .WithMany("AssignedStudents")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("University.Domain.Entities.Professor", "Professor")
                        .WithMany("FeedbackProvided")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.ThesisUpdate", "Update")
                        .WithMany("Feedback")
                        .HasForeignKey("UpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Update");
                });

            modelBuilder.Entity("University.Domain.Entities.Student", b =>
                {
                    b.HasOne("University.Domain.Entities.Professor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("University.Domain.Entities.ThesisTopicAssignment", b =>
                {
                    b.HasOne("University.Domain.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Domain.Entities.ThesisUpdate", b =>
                {
                    b.HasOne("University.Domain.Entities.Student", "Student")
                        .WithMany("ThesisUpdates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Domain.Entities.Professor", b =>
                {
                    b.Navigation("AssignedStudents");

                    b.Navigation("FeedbackProvided");
                });

            modelBuilder.Entity("University.Domain.Entities.Student", b =>
                {
                    b.Navigation("ThesisUpdates");
                });

            modelBuilder.Entity("University.Domain.Entities.ThesisUpdate", b =>
                {
                    b.Navigation("Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
